-- noinspection SqlResolveForFile

CREATE TABLE APP_USERS_COMPANIES
(
  USER_ID      BIGINT NOT NULL,
  COMPANY_ID   BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, COMPANY_ID)
);

ALTER TABLE APP_USERS_COMPANIES
  ADD CONSTRAINT APP_USERS_COMPANIES_AUTHORITY
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY;

ALTER TABLE APP_USERS_COMPANIES
  ADD CONSTRAINT APP_USERS_COMPANIES_USER_
    FOREIGN KEY (USER_ID) REFERENCES USER_;