INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (1, 1);
INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (1, 2);
INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (1, 3);

INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (2, 1);
INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (2, 2);

INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (3, 1);

INSERT INTO APP_USERS_COMPANIES(USER_ID, COMPANY_ID)
VALUES (4, 3);
